import { Meta } from '@storybook/react/types-6-0';
import { Story } from '@storybook/react';
import { RadioProps } from './Radio';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const AllVariations: Story<RadioProps>;
export declare const Default: Story<RadioProps>;
export declare const Description: Story<RadioProps>;
export declare const Required: Story<RadioProps>;
export declare const Checked: Story<RadioProps>;
export declare const ErrorState: Story<RadioProps>;
export declare const Disabled: Story<RadioProps>;
