import { Meta } from '@storybook/react/types-6-0';
import { Story } from '@storybook/react';
import { TextInputProps } from './TextInput';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const AllVariations: Story<TextInputProps>;
export declare const Default: Story<TextInputProps>;
export declare const Message: Story<TextInputProps>;
export declare const Counter: Story<TextInputProps>;
export declare const Required: Story<TextInputProps>;
export declare const Error: Story<TextInputProps>;
export declare const Disabled: Story<TextInputProps>;
