import { Meta } from '@storybook/react/types-6-0';
import { Story } from '@storybook/react';
import { TextareaProps } from './Textarea';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const AllVariations: Story<TextareaProps>;
export declare const Default: Story<TextareaProps>;
export declare const Message: Story<TextareaProps>;
export declare const Counter: Story<TextareaProps>;
export declare const Required: Story<TextareaProps>;
export declare const Error: Story<TextareaProps>;
export declare const Disabled: Story<TextareaProps>;
