export default function Head() {
  return (
		<>
			<title>Create Next App</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />

			<link rel="apple-touch-startup-image" href="https://static.agilitycms.com/favicon/purple/128.png" />

			<link
				rel="apple-touch-icon-precomposed"
				sizes="64x64"
				href="https://static.agilitycms.com/favicon/purple/64.png"
			/>
			<link
				rel="apple-touch-icon-precomposed"
				sizes="128x128"
				href="https://static.agilitycms.com/favicon/purple/128.png"
			/>
			<link
				rel="apple-touch-icon-precomposed"
				sizes="256x256"
				href="https://static.agilitycms.com/favicon/purple/256.png"
			/>
			<link
				rel="apple-touch-icon-precomposed"
				sizes="512x512"
				href="https://static.agilitycms.com/favicon/purple/512.png"
			/>

			<link
				rel="icon"
				type="image/png"
				href="https://static.agilitycms.com/favicon/purple/32.png"
				sizes="32x32"
			/>
			<link
				rel="icon"
				type="image/png"
				href="https://static.agilitycms.com/favicon/purple/64.png"
				sizes="64x64"
			/>
			<link
				rel="icon"
				type="image/png"
				href="https://static.agilitycms.com/favicon/favicon-128x128.png"
				sizes="128x128"
			/>
			<link
				rel="icon"
				type="image/png"
				href="https://static.agilitycms.com/favicon/favicon-256x256.png"
				sizes="256x256"
			/>

			<meta name="application-name" content="Agility" />
		</>
  )
}
