export const data = [
    {
      "key": "f-1056",
      "type": "Asset",
      "title": "Attachments",
      "lazy": true,
      "expanded": false,
      "folder": true,
      "prefix": "Attachments/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 1056,
      "folderID": 0,
      "childNodes": null,
    },
    {
      "key": "f-4134",
      "type": "Asset",
      "title": "custom-field-shared-assets",
      "lazy": false,
      "expanded": true,
      "folder": true,
      "prefix": "custom-field-shared-assets/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 4134,
      "folderID": 0,
      "childNodes": [
        {
          "key": "f-4135",
          "type": "Asset",
          "title": "widen-asset-selector",
          "lazy": false,
          "expanded": false,
          "folder": false,
          "prefix": "custom-field-shared-assets/widen-asset-selector/",
          "iconclass": "fa fa-folder-open-o",
          "galleryID": 0,
          "galleryFolderID": 0,
          "assetID": 4135,
          "folderID": 0,
          "childNodes": null
        }
      ]
    },
    {
      "key": "f-5480",
      "type": "Asset",
      "title": "default-icons",
      "lazy": false,
      "expanded": false,
      "folder": false,
      "prefix": "default-icons/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 5480,
      "folderID": 0,
      "childNodes": null
    },
    {
      "key": "f-1",
      "type": "Asset",
      "title": "images",
      "lazy": true,
      "expanded": false,
      "folder": true,
      "prefix": "images/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 1,
      "folderID": 0,
      "childNodes": null
    },
    {
      "key": "f-5486",
      "type": "Asset",
      "title": "public-app-icons",
      "lazy": false,
      "expanded": false,
      "folder": false,
      "prefix": "public-app-icons/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 5486,
      "folderID": 0,
      "childNodes": null
    },
    {
      "key": "f-4229",
      "type": "Asset",
      "title": "quickstart",
      "lazy": false,
      "expanded": false,
      "folder": false,
      "prefix": "quickstart/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 4229,
      "folderID": 0,
      "childNodes": null
    },
    {
      "key": "f-4286",
      "type": "Asset",
      "title": "scripts",
      "lazy": false,
      "expanded": true,
      "folder": true,
      "prefix": "scripts/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 4286,
      "folderID": 0,
      "childNodes": [
        {
          "key": "f-4290",
          "type": "Asset",
          "title": "monaco-editor",
          "lazy": false,
          "expanded": true,
          "folder": true,
          "prefix": "scripts/monaco-editor/",
          "iconclass": "fa fa-folder-open-o",
          "galleryID": 0,
          "galleryFolderID": 0,
          "assetID": 4290,
          "folderID": 0,
          "childNodes": [
            {
              "key": "f-4291",
              "type": "Asset",
              "title": "min",
              "lazy": true,
              "expanded": false,
              "folder": true,
              "prefix": "scripts/monaco-editor/min/",
              "iconclass": "fa fa-folder-open-o",
              "galleryID": 0,
              "galleryFolderID": 0,
              "assetID": 4291,
              "folderID": 0,
              "childNodes": null
            }
          ]
        },
        {
          "key": "f-4775",
          "type": "Asset",
          "title": "tinymce-4.9.10",
          "lazy": true,
          "expanded": false,
          "folder": true,
          "prefix": "scripts/tinymce-4.9.10/",
          "iconclass": "fa fa-folder-open-o",
          "galleryID": 0,
          "galleryFolderID": 0,
          "assetID": 4775,
          "folderID": 0,
          "childNodes": null
        },
        {
          "key": "f-4979",
          "type": "Asset",
          "title": "tinymce-5",
          "lazy": true,
          "expanded": false,
          "folder": true,
          "prefix": "scripts/tinymce-5/",
          "iconclass": "fa fa-folder-open-o",
          "galleryID": 0,
          "galleryFolderID": 0,
          "assetID": 4979,
          "folderID": 0,
          "childNodes": null
        },
        {
          "key": "f-5118",
          "type": "Asset",
          "title": "tinymce-5-10",
          "lazy": true,
          "expanded": false,
          "folder": true,
          "prefix": "scripts/tinymce-5-10/",
          "iconclass": "fa fa-folder-open-o",
          "galleryID": 0,
          "galleryFolderID": 0,
          "assetID": 5118,
          "folderID": 0,
          "childNodes": null
        }
      ]
    },
    {
      "key": "f-4112",
      "type": "Asset",
      "title": "training-docs",
      "lazy": false,
      "expanded": false,
      "folder": false,
      "prefix": "training-docs/",
      "iconclass": "fa fa-folder-open-o",
      "galleryID": 0,
      "galleryFolderID": 0,
      "assetID": 4112,
      "folderID": 0,
      "childNodes": null
    }
  ]