import { Meta } from "@storybook/react/types-6-0";
import { Story } from "@storybook/react";
import { TextInputAddonProps } from "./TextInputAddon";
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const AllVariations: Story<TextInputAddonProps>;
export declare const Default: Story<TextInputAddonProps>;
export declare const LeadIcon: Story<TextInputAddonProps>;
export declare const TrailAction: Story<TextInputAddonProps>;
export declare const TrailAndLeadIcons: Story<TextInputAddonProps>;
export declare const TrailIcon: Story<TextInputAddonProps>;
export declare const LeadLabel: Story<TextInputAddonProps>;
